"""0001 2 add surname

Revision ID: 90357e6ecc3c
Revises: 412ded38cd55
Create Date: 2025-06-18 17:57:06.697156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90357e6ecc3c'
down_revision = '412ded38cd55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
